[project]
name = "llm-planning-analysis-final-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.72.0",
    "boto3>=1.42.55",
    "numpy>=1.21.2",
    "openai>=2.2.0",
    "pddl==0.2.0",
    "pyyaml==6.0",
    "rich>=14.3.3",
    "setuptools<81.0.0",
    "tarski==0.7.0",
    "torch==2.9.1",
    "transformers>=4.48.0",
    "vertexai>=1.71.1",
    "vllm>=0.2.5",
    "wheel>=0.45.1",
]
